### ISSUE TITLE
Check validity both ERC721 and ERC1155 if they claim to support both EIP165

### ISSUE THREAD

**Issue by 0xjimmy** [DarkFlorist/nft-wallet#18]
https://opensea.io/assets/ethereum/0xa342f5d851e866e18ff98f351f2c6637f4478db5/55464657044963196816950587289035428064568320970692304673817341489688260646912

This ERC1155 contract is detected as an ERC721, but does not support all methods so it throws.
Behavior should be changed so the ERC1155 cases are checked also.

**Comment by MicahZoltu** [comment]
In my research it appears that this contract is both ERC-721 and ERC-1155 compliant.  The problem is that when you lookup the ERC-721 token ID it throws with an incorrect error because no ERC-721 NFT exists with the provided ID.

So I think there are two different errors:
1. If a contract is both ERC-721 and ERC-1155, we will never check to see if an ERC-1155 token exists.
2. When the provided ID doesn't exist, the ERC-721 lookup will incorrectly throw an error saying the contract isn't a valid ERC-721 token when it should throw an error saying the token with that ID doesn't exist.
